package com.scrumpoker.domain.room;

import com.scrumpoker.domain.organization.Organization;
import com.scrumpoker.domain.user.User;
import io.quarkus.hibernate.reactive.panache.PanacheEntityBase;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;

/**
 * Estimation session with 6-character nanoid identifier.
 * Supports soft delete via deleted_at timestamp for audit trail.
 */
@Entity
@Table(name = "room")
@Cacheable
public class Room extends PanacheEntityBase {

    /**
     * Short 6-character nanoid for shareable URLs (e.g., abc123).
     * NOT a UUID - generated by application logic.
     */
    @Id
    @Size(min = 6, max = 6)
    @Column(name = "room_id", length = 6)
    public String roomId;

    /**
     * Nullable to support anonymous room creation.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "owner_id", foreignKey = @ForeignKey(name = "fk_room_owner"))
    public User owner;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_id", foreignKey = @ForeignKey(name = "fk_room_org"))
    public Organization organization;

    @NotNull
    @Size(max = 255)
    @Column(name = "title", nullable = false, length = 255)
    public String title;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "privacy_mode", nullable = false, columnDefinition = "privacy_mode_enum")
    public PrivacyMode privacyMode = PrivacyMode.PUBLIC;

    /**
     * JSONB column: deck_type, timer_enabled, timer_duration_seconds, reveal_behavior, allow_observers.
     * Stored as JSON string, serialized/deserialized by application code.
     */
    @NotNull
    @Column(name = "config", nullable = false, columnDefinition = "jsonb")
    public String config;

    @NotNull
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    public Instant createdAt;

    @NotNull
    @UpdateTimestamp
    @Column(name = "last_active_at", nullable = false)
    public Instant lastActiveAt;

    /**
     * Soft delete timestamp for audit trail.
     * NULL means the room is active, non-NULL means soft-deleted.
     */
    @Column(name = "deleted_at")
    public Instant deletedAt;
}
