package com.scrumpoker.api.rest.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;

/**
 * Request DTO for OAuth2 callback endpoint.
 * Contains authorization code and provider information from OAuth2 flow.
 */
public class OAuthCallbackRequest {

    /**
     * Authorization code from OAuth2 provider.
     */
    @JsonProperty("code")
    @NotBlank(message = "Authorization code is required")
    public String code;

    /**
     * OAuth2 provider name (google or microsoft).
     */
    @JsonProperty("provider")
    @NotBlank(message = "Provider is required")
    @Pattern(regexp = "^(google|microsoft)$",
            message = "Provider must be 'google' or 'microsoft'")
    public String provider;

    /**
     * Redirect URI used in authorization request.
     * Must match the URI registered with the OAuth2 provider.
     */
    @JsonProperty("redirectUri")
    @NotBlank(message = "Redirect URI is required")
    public String redirectUri;

    /**
     * PKCE code verifier generated by frontend.
     * Required for secure OAuth2 authorization code flow.
     * NOTE: This field is not in the current OpenAPI spec but is required
     * by the OAuth2Adapter for PKCE validation.
     */
    @JsonProperty("codeVerifier")
    @NotBlank(message = "Code verifier is required")
    public String codeVerifier;

    /**
     * Default constructor for Jackson deserialization.
     */
    public OAuthCallbackRequest() {
    }

    /**
     * Full constructor for testing.
     *
     * @param code         Authorization code
     * @param provider     OAuth provider name
     * @param redirectUri  Redirect URI
     * @param codeVerifier PKCE code verifier
     */
    public OAuthCallbackRequest(final String code,
                                 final String provider,
                                 final String redirectUri,
                                 final String codeVerifier) {
        this.code = code;
        this.provider = provider;
        this.redirectUri = redirectUri;
        this.codeVerifier = codeVerifier;
    }
}
