package com.scrumpoker.api.rest.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;

/**
 * Request DTO for SSO callback endpoint.
 * Contains authentication data and protocol information from SSO flow (OIDC/SAML2).
 */
public class SsoCallbackRequest {

    /**
     * Authentication data from SSO provider.
     * For OIDC: authorization code
     * For SAML2: Base64-encoded SAML response
     */
    @JsonProperty("code")
    @NotBlank(message = "Authentication code/response is required")
    public String code;

    /**
     * SSO protocol used (oidc or saml2).
     */
    @JsonProperty("protocol")
    @NotBlank(message = "Protocol is required")
    @Pattern(regexp = "^(oidc|saml2)$",
            message = "Protocol must be 'oidc' or 'saml2'")
    public String protocol;

    /**
     * Redirect URI used in authorization request.
     * Required for OIDC flow to validate callback.
     * Optional for SAML2.
     */
    @JsonProperty("redirectUri")
    public String redirectUri;

    /**
     * PKCE code verifier generated by frontend.
     * Required for OIDC protocol.
     * Optional for SAML2.
     */
    @JsonProperty("codeVerifier")
    public String codeVerifier;

    /**
     * User's email address for domain-based organization lookup.
     * Required to match user to organization by email domain.
     */
    @JsonProperty("email")
    @NotBlank(message = "Email is required for domain-based organization lookup")
    public String email;

    /**
     * Default constructor for Jackson deserialization.
     */
    public SsoCallbackRequest() {
    }

    /**
     * Full constructor for testing.
     *
     * @param code         Authentication code/response
     * @param protocol     SSO protocol (oidc or saml2)
     * @param redirectUri  Redirect URI (OIDC only)
     * @param codeVerifier PKCE code verifier (OIDC only)
     * @param email        User's email for domain lookup
     */
    public SsoCallbackRequest(final String code,
                              final String protocol,
                              final String redirectUri,
                              final String codeVerifier,
                              final String email) {
        this.code = code;
        this.protocol = protocol;
        this.redirectUri = redirectUri;
        this.codeVerifier = codeVerifier;
        this.email = email;
    }
}
